name: build

on:
  schedule:
    - cron:  '0 0 * * MON'
  workflow_dispatch:

env:
  IMAGE_NAME: ci-docker-ansible

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible_version:
          - '2.10'
          - '3.4'
          - '4.10'
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: ANSIBLE_VERSION=${{ matrix.ansible_version }} make build

      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.0
        with:
          registry: "ghcr.io/${{ github.repository_owner }}"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=${{ matrix.ansible_version}}-latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          DOCKER_TAG=$IMAGE_ID:$VERSION make push
